### ISSUE TITLE
Better logo

### ISSUE THREAD

**Issue by AdityaKane2001** [AdityaKane2001/arxiv-switch#4]
Need to have a better logo for the extension. Contributions are welcome. 

/cc @sahilkhose

**Comment by RohithBoppey** [comment]
Take a loot at this one: 

![image_2022-08-01_214642860](https://user-images.githubusercontent.com/73538974/182194997-3e78e094-9c31-477d-9fc6-8cbe46ac4490.png)

**Comment by AdityaKane2001** [comment]
@RohithBoppey 

Thanks for putting in the time and effort to make a logo for the extension! Really appreciate it!

If possible could you make the design a bit more noticeable? The logo will be in the top extension bar and so it will not be readable for the users due to its small size. Attaching screenshot for reference.


![Screenshot 2022-08-01 234137](https://user-images.githubusercontent.com/64411306/182214159-be9fab36-247d-4d89-bf4c-54508fc3f578.png)

**Comment by RohithBoppey** [comment]
I'm trying to come up with an idea to it. I don't think just increasing the size of the font would do the work, does it? Have any clues to make it a little unique. If I can use it, I would.

**Comment by RohithBoppey** [comment]
@AdityaKane2001 Check this one out and let me know:

![image](https://user-images.githubusercontent.com/73538974/182220450-d65676ba-7f38-47b8-bc74-caf1a8e1abea.png)

**Comment by sahilkhose** [comment]
@RohithBoppey definitely the larger font size is better now for readability, but I think the core problem is to include some text in the logo in the first place. I feel most of the extensions I use usually just have the initials ('uBlock' has UB; 'arXiv switch' could be AS or AXS?) or it is just a simple image that depicts the essence of the tool. (a puzzle piece for 'Extensions', google calendar logo for 'Button for google calendar', etc)
At this point, I feel a good starting point could even be to adopt the switching arrows independently and work up on that. the arXiv logo, although witty (credits: @AdityaKane2001), doesn't seem to convey the message as even I was unaware that the logo belonged to arXiv.

**Comment by RohithBoppey** [comment]
@sahilkhose Considering your ideas, I have come up with this: 

@AdityaKane2001 Take a look at this:

![image](https://user-images.githubusercontent.com/73538974/182311498-e0e67984-f123-4b38-b8a1-a72e4e4d039e.png)

Since the main focus is PDF, the background is PDF and the technology arxiv is indicated in the _x_ from the image.
Crop as needed.

**Comment by AdityaKane2001** [comment]
@RohithBoppey This one is definitely better. Just one change, it would be great if you could replace the "x" with the arXiv specific X. It looks something as follows:

![image](https://user-images.githubusercontent.com/64411306/182313997-c9634ae2-24f0-40d0-99c5-a03e32b851b5.png)

I think it would also help to invert the color scheme. White background, red outline and the modified X inside of it would be better.

**Comment by AdityaKane2001** [comment]
@sahilkhose WDYT?

**Comment by RohithBoppey** [comment]
> @sahilkhose WDYT?

Yeah, could be possible, let me try.

**Comment by AdityaKane2001** [comment]
@RohithBoppey See updated comment above.

**Comment by RohithBoppey** [comment]
> @RohithBoppey See updated comment above.

Yeah, seems good.

**Comment by RohithBoppey** [comment]
I think this would be sufficient right?

![image](https://user-images.githubusercontent.com/73538974/182363370-6d78fae2-f482-4577-bd25-c7bd254a0911.png)

**Comment by AdityaKane2001** [comment]
@RohithBoppey 

LGTM. One last nit, if you could make the color of the red outline more uniform (it is currently a bit weird at some points). Thanks for your patience on this.

@sahilkhose WDYT?

**Comment by sahilkhose** [comment]
Yeah this looks very good. Along with the uniformity of the color, let's also get a logo to compare if the color of the border is the same as the arXiv X color. Would be lovely if we can have a side by side comparison.

**Comment by RohithBoppey** [comment]
I hope this solves it. 

![image](https://user-images.githubusercontent.com/73538974/182385220-5b6c6d86-1da4-445a-a1f7-d11c336a2c03.png)

By the way, shall I keep a PR now?

**Comment by sahilkhose** [comment]
The same problem from before persists, hoping to get it fixed.

**Comment by AdityaKane2001** [comment]
![image](https://user-images.githubusercontent.com/64411306/182422347-0fafa350-a4e6-4de9-919f-e7f5c190ec82.png)

Please see image for exact location of incorrect color. 

Let's finalize the image here, the PR can be just an open-and-close.

**Comment by RohithBoppey** [comment]
Even I am new to Photoshop, hence I have facing a little difficulty polishing the image. I did what I can do.

![image](https://user-images.githubusercontent.com/73538974/182449754-bdc6fc37-f703-4625-a563-132251bc31fa.png)

Also, I don't think the imperfections would be visible from a distance. Anyways, see this.

**Comment by AdityaKane2001** [comment]
@RohithBoppey

![logo](https://user-images.githubusercontent.com/64411306/182541126-24948bc8-6c4b-445d-821e-3b6421340762.png)
 
I have made some minor changes to the logo. Please complete the following steps an then raise a PR:

1. Crop the logo to a square. Remove the top and bottom white areas completely and the sides partially to make it a square shape. The height of the PDF symbol must be the side length of the square.
2. Make a copy of the image and name it 128.png. Resize the image in this copy to 128x128.
3. You will now have 2 files - logo.png and 128.png. Remove the background of both images using [remove.bg](https://www.remove.bg/).
4. Lastly, add these files to your fork and make a PR. I will approve and merge the same.

**Comment by RohithBoppey** [comment]
I have made a PR. Take a look at it. Thank you.
